/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.gavinhogan.excel

import spock.lang.Specification

class AppTest extends Specification {
    /*def "application has a greeting"() {
        setup:
        def app = new App()

        when:


        then:

    }*//*def "application has a greeting"() {
        setup:
        def app = new App()

        when:


        then:

    }*/
}
